name: G9_exp

on:
  push:
    branches:
      - Proton_G9

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup multiarch
        run: |
          sudo dpkg --add-architecture i386
          sudo mkdir -pm755 /etc/apt/keyrings
          sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
          sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/kinetic/winehq-kinetic.sources
          sudo apt-get update -y
      - name: Install dependencies
        run: >
          sudo apt-get install -y
          gcc-multilib
          ninja-build
          libwine-dev
          libwine-dev:i386
          libegl1-mesa-dev
          libegl1-mesa-dev:i386
          libgl1-mesa-dev
          libgl1-mesa-dev:i386
          libd3dadapter9-mesa-dev
          libd3dadapter9-mesa-dev:i386
      - name: Install meson
        run: |
          pip3 install --user setuptools
          pip3 install --user --upgrade 'pip==20.3.4'
          pip3 install --user 'meson==0.46'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup environment
        run: >
          if test "${GITHUB_REF:0:10}" = "refs/tags/"; then
            echo "RELEASE_TARBALL=/tmp/gallium-nine-standalone-${GITHUB_REF:10}.tar.gz" >> $GITHUB_ENV
          else
            echo "RELEASE_TARBALL=/tmp/gallium-nine-standalone-${GITHUB_SHA:0:8}.tar.gz" >> $GITHUB_ENV
          fi
      - name: Compile
        env:
          WINE32_LIBDIR: /usr/lib/i386-linux-gnu/wine
        run: ./release.sh -o "${RELEASE_TARBALL}" -- -Ddri2=true -Ddistro-independent=true
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.RELEASE_TARBALL }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
