name: G9_exp

on:
  push:
    branches:
      - Proton_G9

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup multiarch
        run: |
          sudo dpkg --add-architecture i386
          sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
          sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources
          sudo apt-get update -y
      - name: Install dependencies
        run: >
          sudo apt-get install -y
          meson
          gcc-multilib
          winehq-stable
          wine-stable-dev
          libdrm-dev:i386
          libx11-dev:i386
          libx11-xcb-dev:i386
          libxcb-present-dev:i386
          libxcb-dri3-dev:i386
          libxcb-dri2-0-dev:i386
          libxcb-xfixes0-dev:i386
          libegl1-mesa-dev:i386
          libgl1-mesa-dev:i386
          libd3dadapter9-mesa-dev:i386
          libdrm-dev
          libx11-dev
          libx11-xcb-dev
          libxcb-present-dev
          libxcb-dri3-dev
          libxcb-dri2-0-dev
          libxcb-xfixes0-dev
          libegl1-mesa-dev
          libgl1-mesa-dev
          libd3dadapter9-mesa-dev
      - name: Install dependencies workaround
        run: |
          sudo apt-get -y download libwine-dev:i386
          sudo dpkg -i --force-depends libwine-dev**.deb
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup environment
        run: >
          if test "${GITHUB_REF:0:10}" = "refs/tags/"; then
            echo "RELEASE_TARBALL=/tmp/gallium-nine-standalone-${GITHUB_REF:10}.tar.gz" >> $GITHUB_ENV
          else
            echo "RELEASE_TARBALL=/tmp/gallium-nine-standalone-${GITHUB_SHA:0:8}.tar.gz" >> $GITHUB_ENV
          fi
      - name: Compile
        env:
          WINE32_LIBDIR: /usr/lib/i386-linux-gnu/wine
        run: ./release.sh -o "${RELEASE_TARBALL}" -- -Ddri2=true -Ddistro-independent=true
      - uses: actions/upload-artifact@v3
        with:
          name: test_out
          path: ./
